#!/usr/bin/env python3
"""
Plot Tracking Data from CSV
Reads a CSV file generated by plot_tracking.py and plots the data.

Usage:
    python plot_csv.py [FILENAME]

If no filename is provided, it will try to find the most recent tracking_data_*.csv file.
"""

import matplotlib.pyplot as plt
import csv
import sys
import os
import glob

def get_latest_csv():
    list_of_files = glob.glob('tracking_data_*.csv') 
    if not list_of_files:
        return None
    return max(list_of_files, key=os.path.getctime)

def plot_csv(filename):
    times = []
    targets = []
    measured = []
    errors = []

    raw_times = []
    
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    t = float(row['time_s'])
                    raw_times.append(t)
                    targets.append(float(row['target_deg']))
                    measured.append(float(row['measured_deg']))
                    errors.append(float(row['error_deg']))
                except ValueError:
                    continue
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return

    if not raw_times:
        print("No valid data found in file.")
        return

    # Process times to make them continuous (handle resets)
    times = []
    time_offset = 0.0
    last_t = -1.0
    
    for t in raw_times:
        if t < last_t:
            # Time reset detected (e.g., from 30s jump back to 0s)
            # Add the last valid time to the offset to continue the timeline
            time_offset = times[-1] + 0.1 # Add 0.1s gap
            # Adjust offset so that (t + new_offset) > times[-1]
            # Actually, simpler: just treat 't' as starting from 0 relative to offset
            # But 't' isn't clean 0. Let's assume t is correct relative time.
            # We want new_t = time_offset + t.
            # But we need to ensure time_offset is correct.
            # Previous Time (Absolute) = times[-1]
            # Previous Time (Relative) = last_t
            # Reset happens.
            # New Absolute should be > times[-1].
            # Let's align the start of the new sequence (t) to be shortly after times[-1].
            # So, time_offset = times[-1] - t + 0.05
            time_offset = times[-1] - t + 0.05
            
        times.append(t + time_offset)
        last_t = t

    print(f"Plotting data from {filename} ({len(times)} points)...")

    # Create plot with two subplots
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True, gridspec_kw={'height_ratios': [3, 1]})
    fig.canvas.manager.set_window_title(f'Tracking Data - {filename}')

    # Main plot: Target vs Measured
    ax1.plot(times, targets, 'b-', label='Target (°)', linewidth=2, alpha=0.8)
    ax1.plot(times, measured, 'r-', label='Measured (°)', linewidth=1.5, alpha=0.8)
    ax1.set_ylabel('Yaw Angle (°)')
    ax1.set_title(f'Wing Sail Tracking Response\nFile: {filename}')
    ax1.legend(loc='upper right')
    ax1.grid(True, alpha=0.3)
    
    # Calculate bounds for main plot
    all_angles = targets + measured
    min_angle = min(all_angles) - 5
    max_angle = max(all_angles) + 5
    ax1.set_ylim(min_angle, max_angle)

    # Error plot
    ax2.plot(times, errors, 'g-', label='Error (°)', linewidth=1)
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Error (°)')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper right')
    
    # Add some statistics
    avg_error = sum([abs(e) for e in errors]) / len(errors)
    max_err = max([abs(e) for e in errors])
    stats_text = f'Mean Abs Error: {avg_error:.2f}°\nMax Abs Error: {max_err:.2f}°'
    ax2.text(0.02, 0.9, stats_text, transform=ax2.transAxes, 
             verticalalignment='top', bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    else:
        # Try to find the latest file in the current directory
        filename = get_latest_csv()
        if not filename:
             # Try looking in the scripts directory if we are at project root
            cwd = os.getcwd()
            if os.path.isdir(os.path.join(cwd, 'scripts')):
                os.chdir('scripts')
                filename = get_latest_csv()
            
            if not filename:
                print("No CSV file provided and no tracking_data_*.csv found.")
                print("Usage: python plot_csv.py [FILENAME]")
                sys.exit(1)
            else:
                print(f"No file specified. Using latest found: {filename}")

    plot_csv(filename)
